# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kuino

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_02c22afb34eb4f288e219d1d4b0fb136 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_906f9d1b20d0468d9460e6085dd639f3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_02c22afb34eb4f288e219d1d4b0fb136 }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kuino'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0b09692e919347bca3937b2e8a85136a }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_02c22afb34eb4f288e219d1d4b0fb136 }}/azure-app-service/windows/parkingpage:${{ github.sha }}'